project_id = "jungfmgsxbayxzptvpky"

[functions.notify-admin-registration]
verify_jwt = false

[functions.send-status-notification]
verify_jwt = true

[functions.verify-admin]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = false

[functions.verify-email]
verify_jwt = false

[functions.trading-chat]
verify_jwt = false

[functions.submit-campaign]
verify_jwt = false

[functions.submit-listing]
verify_jwt = false

[functions.send-newsletter]
verify_jwt = true

[functions.prodigi]
verify_jwt = false

[functions.generate-mockup]
verify_jwt = false

[functions.paymongo-checkout]
verify_jwt = false

[functions.paymongo-webhook]
verify_jwt = false
 
 [functions.activation-checkout]
 verify_jwt = false
 
 [functions.activation-payment-callback]
 verify_jwt = false

[functions.send-payment-reminder]
verify_jwt = false

[functions.listing-checkout]
verify_jwt = false

[functions.venue-registration-checkout]
verify_jwt = false
